version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - '5000:5000'
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: testdb
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: testdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./messages.sql:/docker-entrypoint-initdb.d/messages.sql
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
        
